import type { Locale } from "@/lib/i18n";

/** Copy de homepage. Cifras de producto salen de trips/stats/faq — no de aquí. */
export const homeCopy = {
  es: {
    tagline: "El Pacífico más prístino del mundo.",
    subtitle: "A 20 minutos de Pixvae.",
    description:
      "Viajes de buceo exclusivos al Parque Nacional Coiba, Panamá. Grupos pequeños. Instructores PADI con más de 25 años de experiencia.",
    ctaDates: "Ver fechas disponibles",
    ctaWhatsapp: "Escríbenos por WhatsApp",
    scroll: "Bajar",
    trust: [
      { value: "+25 años", label: "de experiencia" },
      { value: "UNESCO", label: "Patrimonio Coiba" },
      { value: "máx. 12", label: "personas por grupo" },
      { value: "PADI", label: "instructores certificados" },
    ],
    departuresTitle: "Próximas Salidas a Isla Coiba",
    departuresSub: "Grupos de máximo 12 personas. Reserva con 50% de anticipo.",
    from: "Desde",
    perPerson: "USD por persona",
    divesIncluded: "inmersiones incluidas",
    fromPixvae: "Salida desde Pixvae",
    maxGroup: "Grupos máx. 12 personas",
    padi: "Instructores PADI certificados",
    insurance: "Incluye seguro de buceo",
    reserve: "Reservar mi lugar",
    itinerary: "Ver itinerario completo",
    hideItinerary: "Ocultar itinerario",
    includes: "Incluye",
    excludes: "No incluye",
    day: "Día",
    whyKicker: "Parque Nacional Coiba",
    whyTitle: "El Galápagos del Pacífico",
    whyBody:
      "El Parque Nacional Coiba es Patrimonio de la Humanidad UNESCO y uno de los últimos reductos vírgenes del Pacífico. Sus aguas albergan más de 760 especies de peces, y según la temporada es hábitat de tiburones ballena, mantarrayas, delfines, tortugas y ballenas jorobadas. Una biodiversidad que pocas personas en el mundo han explorado bajo el agua — sin garantías de avistamiento: la naturaleza no es predecible.",
    teamTitle: "Los mejores instructores del Pacífico panameño",
    galleryTitle: "Coiba en imágenes",
    galleryNote: "Imágenes ilustrativas de ambiente. No son registro de una salida concreta.",
    galleryCta: "Ver galería completa",
    faqTitle: "Preguntas frecuentes",
    faqAll: "Ver todas las preguntas",
    ctaTitle: "¿Listo para bucear en Coiba?",
    mediaCredit: "Imagen ilustrativa",
    reserveTitle: "Reserva tu lugar",
    reserveLead:
      "El formulario de email llega en la siguiente fase. Hoy tu reserva sale por WhatsApp, directo con Jhon.",
    name: "Nombre",
    email: "Correo",
    trip: "Plan",
    message: "Mensaje",
    sendWa: "Enviar por WhatsApp",
    close: "Cerrar",
    menu: "Menú",
    book: "Reservar",
  },
  en: {
    tagline: "The world's most pristine Pacific.",
    subtitle: "20 minutes from Pixvae.",
    description:
      "Exclusive dive expeditions to Coiba National Park, Panama. Small groups. PADI instructors with over 25 years of experience.",
    ctaDates: "See available dates",
    ctaWhatsapp: "Message us on WhatsApp",
    scroll: "Scroll",
    trust: [
      { value: "25+ years", label: "of experience" },
      { value: "UNESCO", label: "Coiba Heritage" },
      { value: "max 12", label: "divers per group" },
      { value: "PADI", label: "certified instructors" },
    ],
    departuresTitle: "Upcoming departures to Coiba Island",
    departuresSub: "Groups of 12 maximum. Reserve with a 50% deposit.",
    from: "From",
    perPerson: "USD per person",
    divesIncluded: "dives included",
    fromPixvae: "Departs from Pixvae",
    maxGroup: "Max 12 people per group",
    padi: "Certified PADI instructors",
    insurance: "Dive insurance included",
    reserve: "Reserve my spot",
    itinerary: "View full itinerary",
    hideItinerary: "Hide itinerary",
    includes: "Includes",
    excludes: "Does not include",
    day: "Day",
    whyKicker: "Coiba National Park",
    whyTitle: "The Galápagos of the Pacific",
    whyBody:
      "Coiba National Park is a UNESCO World Heritage Site and one of the last wild refuges in the Pacific. Its waters hold more than 760 fish species, and depending on the season it is habitat for whale sharks, manta rays, dolphins, turtles and humpback whales. Biodiversity few people have explored underwater — sightings depend on season and conditions: nature is not predictable.",
    teamTitle: "The finest instructors on Panama's Pacific",
    galleryTitle: "Coiba in pictures",
    galleryNote: "Illustrative atmosphere images. Not a record of a specific departure.",
    galleryCta: "See full gallery",
    faqTitle: "Frequently asked questions",
    faqAll: "See all questions",
    ctaTitle: "Ready to dive Coiba?",
    mediaCredit: "Illustrative image",
    reserveTitle: "Reserve your spot",
    reserveLead:
      "The email form ships in the next phase. Today your reservation goes out on WhatsApp, straight to Jhon.",
    name: "Name",
    email: "Email",
    trip: "Plan",
    message: "Message",
    sendWa: "Send on WhatsApp",
    close: "Close",
    menu: "Menu",
    book: "Book",
  },
} as const;

export function t(locale: Locale) {
  return homeCopy[locale];
}
